draft-thomson-http-oblivious.md
Makes some of my suggestions from #9, and addresses #8 in the process.
For context, I consider the `keyID` variable to be the wire-encoded (length prefixed) thing, and I tried to clarify that here. I don't feel strongly about the way that's written, but I do think it's important that everything sent on the wire is authenticated, including the keyID length.
=> Encapsulate the server response with a nonce.

draft-thomson-http-oblivious.md
I think that "response" for the exporter is better than "secret".
Symmetry.
=> Make the label match the text

draft-thomson-http-oblivious.md
Switches to an 8-bit key identifier here as well.
This format now doesn't need varints.  Yay.
Implemented this in my ohttp library and it's fine.
Closes #20.
=> Add KDF and AEAD identifiers to the message

draft-thomson-http-oblivious.md
This is more background than I would normally like to include, but it
seems prudent at this stage.
The example usage bit might go eventually, but I can see us keeping some
sort of applicability statement.
=> Applicability statement

draft-thomson-http-oblivious.md
Closes #31 and #32.
Given [the parsing code here](https://github.com/martinthomson/ohttp/blob/main/ohttp/src/lib.rs#L255-L264) (either assuming a fixed key ID, or looking up the KEM based on key ID), I think this is a nice simplification. It also authenticates more, even if redundant. (The kemID is already part of the HPKE key schedule.) I implemented this change and it's straightforward.
=> Remove length prefix on fixed-length values.

draft-thomson-http-oblivious.md
The whole mess that is key configuration discovery needs real work.
There are cases where trust suffices, but we can't rely on that here.
What this does is tweak the language to more clearly note the lines of
responsibility for this draft.
I also noted that we didn't talk about trial decryption and tracking, so
I added that.  It seemed like we didn't need to mention multiple keys
with the same identifier twice after that.
=> More clearly dodge responsibility

draft-thomson-http-oblivious.md
But they should.  Consider the case where clients have equal-sized
messages, but are making requests using different key identifiers or
different request targets.  If that information could be linked to
certain clients, encryption would increase the size of the anonymity set
from the perspective of a passive observer for little extra cost.
Closes #56.
=> Proxies don't need TLS to the server

Makefile, draft-ietf-ohai-ohttp.md
This makes the whole `{::date}` thing unnecessary as well.
=> Use the published binary HTTP version

draft-ietf-ohai-ohttp.md
Nk wasn't described properly before.  This improves that, but puts the citations together.
=> Describe Nenc and Nk together.

draft-ietf-ohai-ohttp.md
This is a breaking change, but I think that it's worthwhile.  "request" is an extraordinary generic string and the risk of it being used in another context is too high.
=> Provide better key diversity

draft-ietf-ohai-ohttp.md
Test vectors generated from the [corresponding change in ohttp](https://github.com/martinthomson/ohttp/pull/17).
Closes #85.
Closes #78.
=> Pin encapsulation payload type to message/bhttp

draft-ietf-ohai-ohttp.md
This makes the choice of a 1:1 mapping clear: avoid being used as an open proxy through explicit configuration of your ACLs.
Closes #77.
Closes #60.
cc @tfpauly
=> Elaborate on the fixed mapping between proxy and request resources

draft-ietf-ohai-ohttp.md
Arguably, the TLS one is better, but one notation convention is better than two, so here we go.
Closes #101.
=> Use the QUIC notation for the key config

draft-ietf-ohai-ohttp.md
Truly, the most interesting forwarding is what occurs at the Oblivious
Request Resource, but this is a point of inflexibility that some people
struggle with.  No point in hiding how we might intend for a generic
proxy to operate.  The alternatives people invent are likely to be
worse if we don't at least point in the rough direction of a good
solution.
Closes #105.
=> Point in the direction of arbitrary forwarding

draft-ietf-ohai-ohttp.md
It would be wrong to use "user agent" as this could be used for an HTTP
request made by any client toward any server (using the HTTP
definitions).
Closes #116.
=> Client != HTTP client

draft-ietf-ohai-ohttp.md
Split out from #96, since the shadowban bit needs more consideration in relation to target->proxy signals like rate limits.
Closes #100.
cc @ekr
=> Make clear that proxy metadata must be known to the client

draft-ietf-ohai-ohttp.md
=> Use Proxy-Authorization as an example header from Client to Proxy

draft-ietf-ohai-ohttp.md
Copy-paste error on my behalf trimmed the last three characters from
private keys.  I almost made the same error again.  The output (which I
will add below) wraps in my terminal at exactly that point.  And this
particular terminal treats a wrapped string as two strings: yay.  Bug
report time.
In any case, I didn't miss the extra characters this time.  I think.
```
[TRACE ohttp::nss::hpke] Generated key pair: sk=PrivateKey 3cf36bbc17111f07e816aa895ff42de8d1a029af16580c232a68e15feefa1073 pk=PublicKey a2baf3a20a6c551df011f02e7b5e87afded5f9d584c1071e439abc1cc5ffc345
[TRACE ohttp::test] Config: 010020a2baf3a20a6c551df011f02e7b5e87afded5f9d584c1071e439abc1cc5ffc34500080001000100010003
[TRACE ohttp::nss::hpke] Generated key pair: sk=PrivateKey …
```
=> New new example

draft-ietf-ohai-ohttp.md
We previously put the details from the key configuration (key id, KEM,
KDF, AEAD) in the AAD for the request.  But @davidben noted that this
meant that this wasn't bound to the response.
Analysis shows that this isn't a security problem, but while that
depends on some very reasonable assumptions about how keys are used,
there is no reason not to do better.
Performance-wise, this change is a wash.  The AAD input is now empty,
which should make this a tiny bit faster to execute.  The downside is
that the info is no longer static, which means that it is a tiny bit
slower, especially on the server side where it is harder to just pass a
constant value into SetupBaseR and the bits from the header into the
AAD.  But those are extraordinarily trivial differences.
The spec doesn't really change …
=> Bind HPKE info to the configuration

draft-ietf-ohai-ohttp.md
This includes the time correction piece.  I'm interested in whether
people think that it is OK to include that.  The section could be
removed along with the corresponding IANA piece, but given the
prevalence of clock skew, I'm inclined to leave it in.
=> Integrate request-date stuff

draft-ietf-ohai-ohttp.md
=> Address relay traffic analysis

draft-ietf-ohai-ohttp.md
The text noted in #155 was correct, but we didn't have a single place where we outlined this as a direct requirement.
The day where HTTP presupposes TLS has come for some, but not all of us.  Until then, we can be more careful.
Closes #155.
=> Mandate HTTPS

draft-ietf-ohai-ohttp.md
Most of the text was correct in that we talk about making a request of a
resource.  Where the text refers to making requests of a server, those
usages seem to be correct.
Closes #156.
=> Fixup some "request[s] of" language

draft-ietf-ohai-ohttp.md
Not even once, down from two.
Using cookies is dumb, but we don't need to ban them so directly.  There
are tons of ways in which information from a previous request might leak
across into the current one.  The point is to highlight the risk of
using them.
A direct prohibition doesn't make sense if the use of the cookie is
well understood (not that attaining such an understanding is likely to
be easy).
Closes #160.
=> Don't prohibit cookies

draft-ietf-ohai-ohttp.md
This was the only case we used the TLS-style dot notation, but we don't need to pull in a new concept.
=> Spell it out rather than use the symbol

draft-ietf-ohai-ohttp.md
RFC 9180 does use skR/pkR/skS/skR, so I didn't change everything to use
snake_case, but this is more consistent with how we identify things in
other places.  Also, it reads better and we don't have to grapple with
whether it should be keyId or keyID.
=> Use snake_case for identifiers

draft-ietf-ohai-ohttp.md
In order to do this properly, I decided to capitalize Client where it
refers to an OHTTP Client.  That was a lot of changes.
This adds a beefy appendix to the document, but I have opened issues on xml2rfc that might eventually slim that down.
=> Index on important terms

draft-ietf-ohai-ohttp.md
This starts by moving the good text from #187 to the "Errors" section, where I realized that it duplicated some of that language.  It was more complete, so I merged the two.
I then added some language about what happens to errors prior to decapsulation.  This doesn't define an error signaling format.  Though that might be useful, it is also a lot more work and I'm leery of scope creep in this document.
My view: if you get an error, you have screwed up somewhere.  You probably want to have a human look at what is going on.  The privacy consequences of automated responses are difficult to work out properly.  Hence this proposed change.
Closes #187.
=> A scaled back version of the error signaling changes.

draft-ietf-ohai-ohttp.md
Forwarding an empty request will always yield a failure on the gateway, so just don't do it.
=> Note that the request body MUST be non-empty

draft-ietf-ohai-ohttp.md
This adds a little structure to the section on encapsulation and tries to make the relationship between different media types more distinct.
This builds on top of #191 (which we are going to merge soon) because that hits all the same text and we have already effectively agreed to those changes.
You can review [a single commit](https://github.com/ietf-wg-ohai/oblivious-http/commit/3373bce07660b762050ba34c6051ac8dd86048cd) to see what the substance of these changes are.  Alternatively, just look at the top of the "HPKE Encapsulation" section (the other changes are unrelated).
=> Make the description of encapsulation clearer

draft-ietf-ohai-ohttp.md
We debated this at some length.  This defines an optional-to-use
signaling method for the gateway so that it can inform the client when
the key configuration is not acceptable.  Clients can use this as a
prompt to refresh their configuration.
Closes #194.
=> Define a problem type for key configurations

draft-ietf-ohai-ohttp.md
Sean's question makes this worth noting.
=> HTTP/1.1 provides no "didn't process" signal

draft-ietf-ohai-ohttp.md
This is based on the observation from @squarooticus that we're presuming a specific processing order at the gateway, which is unnecessary.
=> Avoid using "before" for gateway->relay errors

draft-ietf-ohai-ohttp.md
We weren't always capitalizing "Encapsulated Request".  This does more, in direct opposition to the changes in #224.  If we don't take that (it seems we at an impasse there), then we should at least be consistent.
=> More capitalization

draft-ietf-ohai-ohttp.md
As @squarooticus observes in his review, "same entity" is more or less meaningless when it comes to ensuring that forwarding doesn't happen in the clear.  This narrows the recommendation to a concrete "same origin", but notes that even that is not sufficient in all cases.
=> More on unsecured requests

draft-ietf-ohai-ohttp.md
We previously only had figures, which are sort of illustrative only, they don't really work as normative specification. The content of these really needs to have words that describe what was intended.
The definition for the request was already sort-of there, so what I've added is a tiny bit repetitive, but I think that it's OK in this case to have the descriptions at different levels of specificity.
The big error here was that the length field in the key configuration was impossible to decipher.  We never said whether it was length in bytes (what has been implemented) or length in number of items.  The bounds on the field length were not helpful here as they were not correct in any way.  I've corrected this value, but would appreciate a sanity check.
No one identified this as a problem in …
=> Better describe the content of various things

draft-ietf-ohai-ohttp.md
Why is it that media type registration is a journey of discovery each and every time?  It's like the coastline paradox: the closer you get, the more detail resolves.  Also, each requirement makes sense in isolation, but if you need an entire RFC to explain it, maybe something has gone wrong.
=> Murray's AD review

draft-ietf-ohai-ohttp.md
This didn't have subject-object agreement previously.
=> A small grammatical tweak

draft-ietf-ohai-ohttp.md
The client relies on a very specific form of trust here, though maybe they have other means to ensure compliance, it's trust that operates here.
Closes #249.
=> s/ensures/can trust/

draft-ietf-ohai-ohttp.md
This came out of #257, where we realized that the relay padding is useful, but needs to employ different methods than client or gateway. The relay can't use binary HTTP padding; it has to insert stuff at the HTTP layer.  Include citations for padding in those documents.
Note that these citations are slightly misleading.  Most relays won't have access at the level necessary to add that padding.  More likely, the relay will need to do as @chris-wood originally suggested, namely adding fields of an appropriate size.  But we don't have good citations for that, so I'm cheaping out.  (Note that RFC 9112, Section 7.1.1 talks about using chunk extensions for padding, but I'm going to pretend that doesn't exist; it's even less usable than the HTTP/2 and HTTP/3 options.)
=> A relay can pad too

draft-ietf-ohai-ohttp.md
Corrected to mention *response* freshness, with a new citation
Added note about timing of a retry revealing RTT
Corrected figure title grammar
=> Revisions to retry text

draft-ietf-ohai-ohttp.md
Especially where it is unnecessary and misleading.
=> Use "extract" less often

draft-ietf-ohai-ohttp.md
This change tries to emphasize that OHTTP is a protocol between client, relay, and gateway, and that the target is sort of ancillary to the whole thing. It further clarifies that the relay should not act as an open proxy when it's operated by an entity that is separate from the target server.
=> OHTTP is a protocol between client, relay, gateway

draft-ietf-ohai-ohttp.md
This talks about the odd case where target and gateway are separate. The primary insight here is that the target is just a regular HTTP resource and the requests from the gateway aren't special.  Problems only occur if the gateway is privileged in some way.
If abuse comes via the gateway, then the target would ordinary block the client, which tends to affect a bunch of bystanders in this model.  So there is pressure to do something special for the gateway.  In that case, the target is trusting the gateway in some way.  Explain that.
The heading here is the only case where we use the short names of the entities, but I can't stand short headings.
=> Separate target and gateway

draft-ietf-ohai-ohttp.md
This changes the definition of "application/ohttp-keys" in a way that is not backwards compatible, but it ensures that the format is usable once new KEMs are introduced.
=> Length prefix key encoding when there are multiple

draft-ietf-ohai-ohttp.md
The text in Step 1 of section 4.4 states the secret size is max(Nk, Nn) but the pseudo-code below it only mentions Nk. The pseudo-code can be updated. In practice Nk is the same as the max. The ohttp-rs code also already has the explicit max operation.
=> Clarify size of secret exported for reponses
