- draft-thomson-http-oblivious.md
This is mostly a port from ODoH to start. We can modify/tweak as needed going forward.
> Port and modify ODoH encapsulation details.

- draft-thomson-http-oblivious.md
This just expands the text and tries to be explicit about everything.
The one change I've included here is a change from 32 to Nsk for the
exported secret.  I think that's in line with the HPKE intent.
Constants make me nervous.
> Do some basic cleanup for encapsulation

- draft-thomson-http-oblivious.md
A first cut at the intro and the text describing how different entities
might think about each other.
After all this, I'm running short on stuff that might go in security
considerations.  Maybe we should move this new text there so that the
security people can find what they need under a familiar heading.
> Add a bunch of words

- draft-thomson-http-oblivious.md
This is more or less implied already, but it is better to write it down.
I've added stubs for some content types as well.
> Define some HTTP usage

- draft-thomson-http-oblivious.md
Ack individuals here instead of citing?
> Add acknowledgments

- draft-thomson-http-oblivious.md
I've also taken the time to review the text in the (now) security
considerations and expand on some of the responsibilities.  Including
the one where the client needs to authenticate key configurations.
Closes #21.
> Define key configuration format

- draft-thomson-http-binary-message.md
This is fully-featured, which is a little awkward.  We can probably trim this down a little once we have a better handle on the requirements.
> Message format

- draft-thomson-http-binary-message.md
> Response of known length is 1

- draft-thomson-http-oblivious.md
One question we might want to ask (even though I think we have the right answer already) is: should `kemID` be included in AAD?
I also removed the padding text, since we moved that to the bhttp spec.
> Various nits found during implementation.

- draft-thomson-http-binary-message.md
Stupid grammar stuff in the published version.
> There is there is

- draft-thomson-http-oblivious.md
The QUIC linter complained and it is usually right about this sort of
thing.
> Make the picture narrower

- draft-thomson-http-oblivious.md
Just a missing word and some stuff that seemed like it could be better.
> Small tweaks

- draft-thomson-http-oblivious.md
This isn't anything that special, but this is a case where a bunch of
our established defenses don't work.
> Add text on replay

- draft-thomson-http-oblivious.md
And recommend key rotation as a mitigation strategy.
Closes #41.
Closes #39.
> Document post-compromise security properties

- draft-thomson-http-oblivious.md
> Discuss linkability concerns (without going into the weeds).

- draft-thomson-http-oblivious.md
The encapsulation of responses isn't *really* HPKE.  The rest are just
tweaks.
> Small cleanups

- draft-thomson-http-oblivious.md
This was vague enough that an example might help.
> Give one example of identifying information.

- draft-thomson-http-oblivious.md
I wanted to add more then just interception text here.  So I added a
little about performance and the ODoH study made some of those costs
clear enough to cite.
I anticipate this section growing over time.  Some of the material we
might add is already in other sections of the doc (DoS management at the
proxy, for example), but we might move that around some.  I also expect
the working group to focus rather narrowly on this topic.
Let's leave this open so that we have something to point to for IETF discussions.
> A start on operation and deployment stuff

- draft-thomson-http-binary-message.md
> Malformed definition was bad grammar

- draft-thomson-http-oblivious.md
This may not be obvious, so perhaps good to note.
> Note that certain client policies are incompatible with OHTTP.

- draft-thomson-ohai-ohttp.md
> AAD length

- .note.xml
- draft-ietf-ohai-ohttp.md
Fix the area and workgroup pieces (which I neglected before) and use the new feature.
> Automatic update of venue information

- draft-ietf-ohai-ohttp.md
> Move padding to binary HTTP messages

- draft-ietf-ohai-ohttp.md
> Key consistency informative reference

- draft-ietf-ohai-ohttp.md
> Add some more use cases

- draft-ietf-ohai-ohttp.md
Let's be clearer about what it means to proxy here.  Also, since it is
the same text, talk about TLS assumptions more directly.
This will interact poorly with #96.  Sorry about that @chris-wood.
Closes #106.
Closes #102.
> Generic intermediary text

- draft-ietf-ohai-ohttp.md
Is this what you had in mind @ekr?
Closes #103.
> Move the conventions down a little bit

- draft-ietf-ohai-ohttp.md
cc @bemasc, @tfpauly
Closes #115
> Clarify URIs in the appendix example

- .gitignore
- draft-ietf-ohai-ohttp.md
> New example

- draft-ietf-ohai-ohttp.md
> Update terminology to align with functionality

- draft-ietf-ohai-ohttp.md
Closes #114.
This is a lot of words to explain the point, so I'm happy to take simplifying suggestions.
cc @tireddy2
> Add text about privacy considerations that come from differential treatment

- draft-ietf-ohai-ohttp.md
@bifurcation noted that it was important to note that the Gateway needs
to be trusted if gateway != target.  As a practical matter, that means
that you probably want gateway == target.
> Add text about deployment assumptions for servers

- draft-ietf-ohai-ohttp.md
> Add text about consistency and privacy reduction

- draft-ietf-ohai-ohttp.md
> More differential treatment

- draft-ietf-ohai-ohttp.md
I already wrote this up, so maybe it's OK to do now.
Closes #135.
> Move media type registrations to the bottom

- draft-ietf-ohai-ohttp.md
> Request encapsulation pseudocode fix.

- draft-ietf-ohai-ohttp.md
I found this helpful, do with it what you will.
> Rework the intro/abstract a bit

- draft-ietf-ohai-ohttp.md
This wouldn't have been anywhere near as good without their input.
> Ack Lucas and Tommy

- draft-ietf-ohai-ohttp.md
This would have been easier had I not forgotten how to do this.
Closes #163.
> Fix HTTP/2 and /3 references

- draft-ietf-ohai-ohttp.md
This was truly buried.  Let's not hide it.
Closes #164.
> Add a heading for the date problem type registration

- draft-ietf-ohai-ohttp.md
> Reword text about delays and traffic analysis

- draft-ietf-ohai-ohttp.md
So add some forward references.
Closes #161.
> A bunch of the real usage requirements come later

- draft-ietf-ohai-ohttp.md
> Match prose and pseudocode for response encap

- draft-ietf-ohai-ohttp.md
> Swap last two paragraphs of HTTP usage

- draft-ietf-ohai-ohttp.md
Especially when we already address this point a few paragraphs above and
we then directly contradict it in the next one.
> Remove bit about protection

- draft-ietf-ohai-ohttp.md
> Define HPKE-dependent pieces correctly

- draft-ietf-ohai-ohttp.md
This makes them easier to handle
> Trim spacing of registrations

- draft-ietf-ohai-ohttp.md
Pretty much what you might expect; see Section 7.6 of [HTTP].
@LPardue, WDYT?
> What happens when there is no response

- draft-ietf-ohai-ohttp.md
These bits are not connected to the rest of it and are unambiguously good.
> Take the easy bits of #183

- draft-ietf-ohai-ohttp.md
Might as well get it out there.
Also, apparently we need more mustaches.
> Acknowledge Ralph

- draft-ietf-ohai-ohttp.md
This is a lot more disruptive, but I think it is a clearer description
of how you might repurpose this design.
I'm still a little unsure about using application/dns-message, but I can
live with it.
> This might be a clearer version of Tommy's change

- draft-ietf-ohai-ohttp.md
> Fix duplicate references

- draft-ietf-ohai-ohttp.md
> Use a less circular definition of Client

- draft-ietf-ohai-ohttp.md
> Fix up some nits

- draft-ietf-ohai-ohttp.md
> Add pointers to the relevant HPKE registries

- draft-ietf-ohai-ohttp.md
Remove a "MUST" in this sentence and lean more heavily on the requirement later.
Closes #211.
> There might extra fields

- draft-ietf-ohai-ohttp.md
Might as well say that.
Closes #208.
> This error is a 4xx

- draft-ietf-ohai-ohttp.md
> Be a little clearer about exporter inputs

- draft-ietf-ohai-ohttp.md
> There is no need to use 'OHTTP'

- draft-ietf-ohai-ohttp.md
This really just needs a good explanation of what might happen.
Closes #212.
> No SHOULD for time slop

- draft-ietf-ohai-ohttp.md
Suggestion to fix my ARTART review nits.
> ARTART review nits

- draft-ietf-ohai-ohttp.md
> It is simply 'comprises'

- draft-ietf-ohai-ohttp.md
> IANA prefer IETF as change controller

- draft-ietf-ohai-ohttp.md
Based on feedback from @squarooticus and his TSV directorate review.
> Work a little on terminology

- draft-ietf-ohai-ohttp.md
Lots of little things here, but very good, all of them.
> Editorial nits from Peter Yee

- draft-ietf-ohai-ohttp.md
> Roman's review feedback

- draft-ietf-ohai-ohttp.md
> Include key configuration description in the registration

- draft-ietf-ohai-ohttp.md
YES rather than DISCUSS is good.  Good feedback is gooder.
> Some tweaks from Martin Duke's review

- draft-ietf-ohai-ohttp.md
Dingledine2004 -> DMS2004
ODoH -> ODOH-PETS
Closes #246.
Closes #251.
> Update reference labels

- draft-ietf-ohai-ohttp.md
> The gateway can pad too

- draft-ietf-ohai-ohttp.md
"and a set HPKE" => "and a set of HPKE"
> nit: Add a preposition to complete the sentence.

- draft-ietf-ohai-ohttp.md
This isn't a suggestion, it's a real risk to consider.
> Going with "need to" over "should"

- draft-ietf-ohai-ohttp.md
> The client selects a KDF and AEAD combination

- draft-ietf-ohai-ohttp.md
Provides a range of values for the length field and uses repetition for the values of algorithms.
Closes #270.
> Include a more precise definition for key config

- draft-ietf-ohai-ohttp.md
The gateway was a little too far off centre for my comfort here.  This puts it a little closer to the Target, which is nicer, I think.
> Tweak diagram alignment

- draft-ietf-ohai-ohttp.md
Line wrapping
Splitting a very long sentence
s/For example/In particular/
cc @mnot
> Editorial fixes on top of #286
